export const completeData = {
    "id": "1",
    "position": "VP",
    "name": "John",
    "reports": [
        {
            "id": "2",
            "position": "Senior Director",
            "name": "Max",
            "reports": [
                {
                    "id": "3",
                    "position": "Director",
                    "name": "Craig",
                    "reports": [
                        {
                            "id": "4",
                            "position": "Manager",
                            "name": "Tim",
                            "performanceRating": "ME",
                            "previousEWSRating": "LR",
                            "talentType": "HC",
                            "projectDependency": "MC",
                            "mentalHealth": "HR",
                            "careerOpportunities": "MR",
                            "motivation": "MR",
                            "personal": "MR",
                            "ewsRating": "MR",
                            "managerRating": "MR",
                            "trigger": "CO - No growth",
                            "reports": [
                                {
                                    "id": "5",
                                    "position": "Team Member",
                                    "name": "Mathas",
                                    "performanceRating": "ME",
                                    "previousEWSRating": "LR",
                                    "talentType": "HC",
                                    "projectDependency": "MC",
                                    "mentalHealth": "HR",
                                    "careerOpportunities": "MR",
                                    "motivation": "MR",
                                    "personal": "MR",
                                    "ewsRating": "MR",
                                    "managerRating": "MR",
                                    "trigger": "CO - No growth"
                                },
                                {
                                    "id": "6",
                                    "position": "Team Member",
                                    "name": "David",
                                    "performanceRating": "EE",
                                    "previousEWSRating": "HR",
                                    "talentType": "MC",
                                    "projectDependency": "MC",
                                    "mentalHealth": "MR",
                                    "careerOpportunities": "LR",
                                    "motivation": "LR",
                                    "personal": "MR",
                                    "ewsRating": "MR",
                                    "managerRating": "LR",
                                    "trigger": "MH - Unrealistic Expectations"
                                },
                                {
                                    "id": "7",
                                    "position": "Team Member",
                                    "name": "Chris",
                                    "performanceRating": "ME",
                                    "previousEWSRating": "MR",
                                    "talentType": "MC",
                                    "projectDependency": "HC",
                                    "mentalHealth": "LR",
                                    "careerOpportunities": "HR",
                                    "motivation": "HR",
                                    "personal": "LR",
                                    "ewsRating": "MR",
                                    "managerRating": "HR",
                                    "trigger": "PD - Dependency risk"
                                },
                                {
                                    "id": "8",
                                    "position": "Team Member",
                                    "name": "Rickey",
                                    "performanceRating": "EE",
                                    "previousEWSRating": "LR",
                                    "talentType": "LC",
                                    "projectDependency": "LC",
                                    "mentalHealth": "LR",
                                    "careerOpportunities": "MR",
                                    "motivation": "MR",
                                    "personal": "HR",
                                    "ewsRating": "LR",
                                    "managerRating": "MR",
                                    "trigger": "PR_personalReason"
                                },
                                {
                                    "id": "9",
                                    "position": "Team Member",
                                    "name": "Nortan",
                                    "performanceRating": "EE",
                                    "previousEWSRating": "LR",
                                    "talentType": "LC",
                                    "projectDependency": "LC",
                                    "mentalHealth": "LR",
                                    "careerOpportunities": "MR",
                                    "motivation": "MR",
                                    "personal": "HR",
                                    "ewsRating": "LR",
                                    "managerRating": "MR",
                                    "trigger": "PR_personalReason"
                                }
                            ]
                        },
                        {
                            "id": "10",
                            "position": "Manager",
                            "name": "Kurt",
                            "performanceRating": "EE",
                            "previousEWSRating": "HR",
                            "talentType": "MC",
                            "projectDependency": "LC",
                            "mentalHealth": "MR",
                            "careerOpportunities": "LR",
                            "motivation": "LR",
                            "personal": "MR",
                            "ewsRating": "MR",
                            "managerRating": "LR",
                            "trigger": "PD - Project delay risk",
                            "reports": [{
                                "id": "11",
                                "position": "Team Member",
                                "name": "Jezza",
                                "performanceRating": "ME",
                                "previousEWSRating": "LR",
                                "talentType": "HC",
                                "projectDependency": "MC",
                                "mentalHealth": "HR",
                                "careerOpportunities": "MR",
                                "motivation": "MR",
                                "personal": "MR",
                                "ewsRating": "MR",
                                "managerRating": "MR",
                                "trigger": "CO - No growth"
                            },
                            {
                                "id": "12",
                                "position": "Team Member",
                                "name": "Mitchell",
                                "performanceRating": "EE",
                                "previousEWSRating": "HR",
                                "talentType": "MC",
                                "projectDependency": "MC",
                                "mentalHealth": "MR",
                                "careerOpportunities": "LR",
                                "motivation": "LR",
                                "personal": "MR",
                                "ewsRating": "MR",
                                "managerRating": "LR",
                                "trigger": "MH - Unrealistic Expectations"
                            },
                            {
                                "id": "13",
                                "position": "Team Member",
                                "name": "Mike",
                                "performanceRating": "ME",
                                "previousEWSRating": "MR",
                                "talentType": "MC",
                                "projectDependency": "HC",
                                "mentalHealth": "LR",
                                "careerOpportunities": "HR",
                                "motivation": "HR",
                                "personal": "LR",
                                "ewsRating": "MR",
                                "managerRating": "HR",
                                "trigger": "PD - Dependency risk"
                            },
                            {
                                "id": "14",
                                "position": "Team Member",
                                "name": "Alton",
                                "performanceRating": "EE",
                                "previousEWSRating": "LR",
                                "talentType": "LC",
                                "projectDependency": "LC",
                                "mentalHealth": "LR",
                                "careerOpportunities": "MR",
                                "motivation": "MR",
                                "personal": "HR",
                                "ewsRating": "LR",
                                "managerRating": "MR",
                                "trigger": "PR_personalReason"
                            }]
                        },
                        {
                            "id": "29",
                            "position": "Team Member",
                            "name": "Ally",
                            "performanceRating": "ME",
                            "previousEWSRating": "LR",
                            "talentType": "HC",
                            "projectDependency": "MC",
                            "mentalHealth": "HR",
                            "careerOpportunities": "MR",
                            "motivation": "MR",
                            "personal": "MR",
                            "ewsRating": "MR",
                            "managerRating": "MR",
                            "trigger": "CO - No growth"
                        },
                        {
                            "id": "30",
                            "position": "Team Member",
                            "name": "Felix",
                            "performanceRating": "ME",
                            "previousEWSRating": "LR",
                            "talentType": "HC",
                            "projectDependency": "MC",
                            "mentalHealth": "HR",
                            "careerOpportunities": "MR",
                            "motivation": "MR",
                            "personal": "MR",
                            "ewsRating": "MR",
                            "managerRating": "MR",
                            "trigger": "CO - No growth"
                        },
                        {
                            "id": "31",
                            "position": "Team Member",
                            "name": "Piper",
                            "performanceRating": "ME",
                            "previousEWSRating": "LR",
                            "talentType": "HC",
                            "projectDependency": "MD",
                            "mentalHealth": "HR",
                            "careerOpportunities": "MR",
                            "motivation": "MR",
                            "personal": "MR",
                            "ewsRating": "MR",
                            "managerRating": "MR",
                            "trigger": "CO - No growth"
                        }
                    ]
                },
                {
                    "id": "15",
                    "position": "Director",
                    "name": "Shon",
                    "reports": [
                        {
                            "id": "16",
                            "position": "Manager",
                            "name": "Sage",
                            "performanceRating": "EE",
                            "previousEWSRating": "MR",
                            "talentType": "HC",
                            "projectDependency": "MC",
                            "mentalHealth": "LR",
                            "careerOpportunities": "HR",
                            "motivation": "HR",
                            "personal": "MR",
                            "ewsRating": "MR",
                            "managerRating": "HR",
                            "trigger": "PR_healthIssues",
                            "reports": [
                                {
                                  "id": "36",
                                  "position": "Team Member",
                                  "name": "Truman",
                                  "performanceRating": "EE",
                                  "previousEWSRating": "LR",
                                  "talentType": "DP",
                                  "projectDependency": "MC",
                                  "mentalHealth": "LR",
                                  "careerOpportunities": "MR",
                                  "motivation": "MR",
                                  "personal": "LR",
                                  "ewsRating": "MR",
                                  "managerRating": "MR",
                                  "trigger": "None"
                                },
                                {
                                  "id": "37",
                                  "position": "Team Member",
                                  "name": "Digby",
                                  "performanceRating": "ME",
                                  "previousEWSRating": "LR",
                                  "talentType": "HC",
                                  "projectDependency": "LC",
                                  "mentalHealth": "MR",
                                  "careerOpportunities": "LR",
                                  "motivation": "LR",
                                  "personal": "MR",
                                  "ewsRating": "MR",
                                  "managerRating": "MR",
                                  "trigger": "MH_Anxiety"
                                },
                                {
                                  "id": "18",
                                  "position": "Team Member",
                                  "name": "Dale",
                                  "performanceRating": "EE",
                                  "previousEWSRating": "LR",
                                  "talentType": "VI",
                                  "projectDependency": "HC",
                                  "mentalHealth": "LR",
                                  "careerOpportunities": "HR",
                                  "motivation": "HR",
                                  "personal": "LR",
                                  "ewsRating": "LR",
                                  "managerRating": "LR",
                                  "trigger": "None"
                                },
                                {
                                  "id": "19",
                                  "position": "Team Member",
                                  "name": "Kevin",
                                  "performanceRating": "ME",
                                  "previousEWSRating": "MR",
                                  "talentType": "DP",
                                  "projectDependency": "MC",
                                  "mentalHealth": "LR",
                                  "careerOpportunities": "MR",
                                  "motivation": "LR",
                                  "personal": "HR",
                                  "ewsRating": "MR",
                                  "managerRating": "MR",
                                  "trigger": "None"
                                }
                              ]
                        },
                        {
                            "id": "17",
                            "position": "Manager",
                            "name": "Ripley",
                            "performanceRating": "ME",
                            "previousEWSRating": "LR",
                            "talentType": "MC",
                            "projectDependency": "HC",
                            "mentalHealth": "MR",
                            "careerOpportunities": "MR",
                            "motivation": "LR",
                            "personal": "MR",
                            "ewsRating": "MR",
                            "managerRating": "MR",
                            "trigger": "Motivation - Career stagnation",
                            "reports": [
                                {
                                    "id": "40",
                                    "position": "Team Member",
                                    "name": "Pearl",
                                    "performanceRating": "", 
                                    "previousEWSRating": "",
                                    "talentType": "",
                                    "projectDependency": "",
                                    "mentalHealth": "",
                                    "careerOpportunities": "",
                                    "motivation": "",
                                    "personal": "",
                                    "ewsRating": "",
                                    "managerRating": "",
                                    "trigger": ""
                                  },
                                  {
                                    "id": "41",
                                    "position": "Team Member",
                                    "name": "Dan",
                                    "performanceRating": "", 
                                    "previousEWSRating": "",
                                    "talentType": "",
                                    "projectDependency": "",
                                    "mentalHealth": "",
                                    "careerOpportunities": "",
                                    "motivation": "",
                                    "personal": "",
                                    "ewsRating": "",
                                    "managerRating": "",
                                    "trigger": ""
                                  },
                                  {
                                    "id": "42",
                                    "position": "Team Member",
                                    "name": "Bret",
                                    "performanceRating": "", 
                                    "previousEWSRating": "",
                                    "talentType": "",
                                    "projectDependency": "",
                                    "mentalHealth": "",
                                    "careerOpportunities": "",
                                    "motivation": "",
                                    "personal": "",
                                    "ewsRating": "",
                                    "managerRating": "",
                                    "trigger": ""
                                  },
                                  {
                                    "id": "43",
                                    "position": "Team Member",
                                    "name": "Pearl",
                                    "performanceRating": "", 
                                    "previousEWSRating": "",
                                    "talentType": "",
                                    "projectDependency": "",
                                    "mentalHealth": "",
                                    "careerOpportunities": "",
                                    "motivation": "",
                                    "personal": "",
                                    "ewsRating": "",
                                    "managerRating": "",
                                    "trigger": ""
                                  }
                            ]
                        },
                        {
                            "id": "26",
                            "position": "Team Member",
                            "name": "Derby",
                            "performanceRating": "ME",
                            "previousEWSRating": "LR",
                            "talentType": "HC",
                            "projectDependency": "MD",
                            "mentalHealth": "HR",
                            "careerOpportunities": "MR",
                            "motivation": "MR",
                            "personal": "MR",
                            "ewsRating": "MR",
                            "managerRating": "MR",
                            "trigger": "CO - No growth"
                        },
                        {
                            "id": "27",
                            "position": "Team Member",
                            "name": "George",
                            "performanceRating": "ME",
                            "previousEWSRating": "LR",
                            "talentType": "HC",
                            "projectDependency": "MD",
                            "mentalHealth": "HR",
                            "careerOpportunities": "MR",
                            "motivation": "MR",
                            "personal": "MR",
                            "ewsRating": "MR",
                            "managerRating": "MR",
                            "trigger": "CO - No growth"
                        },
                        {
                            "id": "28",
                            "position": "Team Member",
                            "name": "Lexi",
                            "performanceRating": "ME",
                            "previousEWSRating": "LR",
                            "talentType": "HC",
                            "projectDependency": "MD",
                            "mentalHealth": "HR",
                            "careerOpportunities": "MR",
                            "motivation": "MR",
                            "personal": "MR",
                            "ewsRating": "MR",
                            "managerRating": "MR",
                            "trigger": "CO - No growth"
                        }
                    ]
                }
            ]
        }
    ]
};

export const RISK_RATING: any = {
    "HR": "High Risk",
    "MR": "Medium Risk",
    "LR": "Low Risk"
};
export const CRITICALITY_RATING: any = {
    "HC": "High Critical",
    "MC": "Medium Critical",
    "LC": "Low Critical",
};
export const PERFORMANCE_RATING: any = {
    "ME": "Meets Expectation",
    "EE": "Exceed Expectation",
    "DE": "Do not meet Expectation"
};

export const TRIGGER: any = {
    "CO_compensation": "CO - Compensation",
    "CO_benefits": "CO - Benefits",
    "CO_lackOfRoleClarity": "CO - Lack Of role clarity",
    "CO_noInternalOpportunities": "CO - No Internal Opportunities",
    "CO_betterRolw": "CO - Better Role",
    "CO_onSiteOpportunity": "CO - Onsite Opportunity",
    "CO_noGrowth": "CO - No growth",
    "MH_workLoad": "MH - Work Load / Burnout",
    "MH_concernsWithManager": "MH - Concerns with Manager",
    "MH_concernsWithPeers": "MH - Concerns with peers",
    "MH_unrealisticExpectations": "MH - Unrealistic Expectations",
    "MH_constChangeInProj": "MH - Constant changes in Projects",
    "MH_personalReason": "MH - Personal Reasons",
    "MH_healthIssues": "MH - Health Issues",
    "MH_depression": "MH - Depression",
    "MH_financialStress": "MH - Financial Stress",
    "MH_anxiety": "MH - Anxiety",
    "MH_feelingIncompitent": "MH - Feeling Incompetant ",
    "MH_workEnvironment": "MH - Work Environment",
    "MT_training": "MT - Training",
    "MT_rewards&Recognition": "MT - Rewards and Recognition",
    "MT_teamDynamics": "MT - Team Dynamics",
    "MT_skillSetMismatch": "MT - Skill set mismatch",
    "MT_uncomfortableShift": "MT - Uncomfortable Shift",
    "MT_projectConcerns": "MT -  Project Concerns",
    "MT_orgCulture": "MT - Org Culture",
    "MT_returnToOffice": "MT - Return to Office",
    "PR_meternity": "PR - Maternity",
    "PR_relocating": "PR - Relocating",
    "PR_marriage": "PR - Marriage",
    "PR_higherEducation": "PR - Higher Education",
    "PR_sabatical": "PR - Sabatical",
    "PR_personalReason": "PR - Personal Reasons",
    "PR_healthIssues": "PR - Health Issues"
}